//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_CounterTexts
    {
        public int pkID { get; set; }
        public string blogCounterFa { get; set; }
        public string projectCounterFa { get; set; }
        public string teamCounterFa { get; set; }
        public string blogCounterEn { get; set; }
        public string projectCounterEn { get; set; }
        public string teamCounterEn { get; set; }
    }
}
