//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_HomeAbout
    {
        public int pkID { get; set; }
        public string MainTitleFa { get; set; }
        public string MainPgFa { get; set; }
        public string MainTitleEn { get; set; }
        public string MainPgEn { get; set; }
        public string Title01Fa { get; set; }
        public string Title02Fa { get; set; }
        public string Title03Fa { get; set; }
        public string Title04Fa { get; set; }
        public string Title01En { get; set; }
        public string Title02En { get; set; }
        public string Title03En { get; set; }
        public string Title04En { get; set; }
    }
}
