//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Header
    {
        public int pkID { get; set; }
        public string logoName { get; set; }
        public string homeFa { get; set; }
        public string aboutFa { get; set; }
        public string projectsFa { get; set; }
        public string contactFa { get; set; }
        public string teamFa { get; set; }
        public string blogFa { get; set; }
        public string homeEn { get; set; }
        public string aboutEn { get; set; }
        public string projectsEn { get; set; }
        public string contactEn { get; set; }
        public string teamEn { get; set; }
        public string blogEn { get; set; }
        public string logoAlt { get; set; }
    }
}
