//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_TopOfCounter
    {
        public int pkID { get; set; }
        public string t1fa { get; set; }
        public string t2fa { get; set; }
        public string t3fa { get; set; }
        public string p1fa { get; set; }
        public string p2fa { get; set; }
        public string p3fa { get; set; }
        public string t1en { get; set; }
        public string t2en { get; set; }
        public string t3en { get; set; }
        public string p1en { get; set; }
        public string p2en { get; set; }
        public string p3en { get; set; }
    }
}
