//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Team()
        {
            this.Table_Blogs = new HashSet<Table_Blogs>();
        }
    
        public int tID { get; set; }
        public string tNameFamily { get; set; }
        public string tDes { get; set; }
        public string tPhoto { get; set; }
        public Nullable<int> fkRole { get; set; }
        public string tInstagram { get; set; }
        public string tLinkedin { get; set; }
        public string tSkill1 { get; set; }
        public string tSkill2 { get; set; }
        public string tSkill3 { get; set; }
        public string tSkill4 { get; set; }
        public string tTitle { get; set; }
        public string lang { get; set; }
    
        public virtual Table_Roles Table_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Blogs> Table_Blogs { get; set; }
    }
}
