//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_AboutTitle
    {
        public int pkID { get; set; }
        public string AbtSloganFa { get; set; }
        public string AbtTitleFa { get; set; }
        public string AbtParagFa { get; set; }
        public string AbtSloganEn { get; set; }
        public string AbtTitleEn { get; set; }
        public string AbtParagEn { get; set; }
    }
}
