//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Blogs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Blogs()
        {
            this.Table_BlogImages = new HashSet<Table_BlogImages>();
        }
    
        public int bID { get; set; }
        public string bName { get; set; }
        public string bTitle { get; set; }
        public string bContent { get; set; }
        public Nullable<int> bCategory { get; set; }
        public string bKeywords { get; set; }
        public Nullable<int> bWriter { get; set; }
        public string bMainPic { get; set; }
        public string bCreatedAt { get; set; }
        public string language { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_BlogImages> Table_BlogImages { get; set; }
        public virtual Table_Team Table_Team { get; set; }
        public virtual Table_BlogCategory Table_BlogCategory { get; set; }
    }
}
