//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ProjectList
    {
        public int pID { get; set; }
        public string pName { get; set; }
        public string pDes { get; set; }
        public string pMainPic { get; set; }
        public int pCategory { get; set; }
        public string pClient { get; set; }
        public string DoneDate { get; set; }
        public string Cname { get; set; }
        public string lang { get; set; }
        public string CnameEn { get; set; }
    }
}
