//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BlogNcat
    {
        public int bID { get; set; }
        public string bName { get; set; }
        public string bTitle { get; set; }
        public string bContent { get; set; }
        public Nullable<int> bCategory { get; set; }
        public string bKeywords { get; set; }
        public Nullable<int> bWriter { get; set; }
        public string bMainPic { get; set; }
        public string bCreatedAt { get; set; }
        public string language { get; set; }
        public string tNameFamily { get; set; }
        public string tPhoto { get; set; }
        public string tTitle { get; set; }
        public string bcName { get; set; }
        public string bcNameEn { get; set; }
    }
}
