//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_TeamRole
    {
        public int tID { get; set; }
        public string tNameFamily { get; set; }
        public string tDes { get; set; }
        public string tPhoto { get; set; }
        public Nullable<int> fkRole { get; set; }
        public string tInstagram { get; set; }
        public string tLinkedin { get; set; }
        public string tSkill1 { get; set; }
        public string tSkill2 { get; set; }
        public string tSkill3 { get; set; }
        public string tSkill4 { get; set; }
        public string tTitle { get; set; }
        public string pkRole { get; set; }
        public string roleDes { get; set; }
        public string lang { get; set; }
    }
}
