//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortoWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortoDB1 : DbContext
    {
        public PortoDB1()
            : base("name=PortoDB1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_BlogImages> Table_BlogImages { get; set; }
        public virtual DbSet<Table_Category> Table_Category { get; set; }
        public virtual DbSet<Table_Members> Table_Members { get; set; }
        public virtual DbSet<Table_Pages> Table_Pages { get; set; }
        public virtual DbSet<Table_ProjectImage> Table_ProjectImage { get; set; }
        public virtual DbSet<Table_Roles> Table_Roles { get; set; }
        public virtual DbSet<Table_siteInfo> Table_siteInfo { get; set; }
        public virtual DbSet<Table_Header> Table_Header { get; set; }
        public virtual DbSet<Table_HomeAbout> Table_HomeAbout { get; set; }
        public virtual DbSet<Table_ProjTeam> Table_ProjTeam { get; set; }
        public virtual DbSet<Table_BottomIndex> Table_BottomIndex { get; set; }
        public virtual DbSet<Table_AboutTitle> Table_AboutTitle { get; set; }
        public virtual DbSet<Table_TopOfCounter> Table_TopOfCounter { get; set; }
        public virtual DbSet<Table_CounterTexts> Table_CounterTexts { get; set; }
        public virtual DbSet<Table_UnderOFCounter> Table_UnderOFCounter { get; set; }
        public virtual DbSet<Table_Messages> Table_Messages { get; set; }
        public virtual DbSet<Table_Banner> Table_Banner { get; set; }
        public virtual DbSet<Table_Projects> Table_Projects { get; set; }
        public virtual DbSet<View_ProjectList> View_ProjectList { get; set; }
        public virtual DbSet<Table_Team> Table_Team { get; set; }
        public virtual DbSet<View_TeamRole> View_TeamRole { get; set; }
        public virtual DbSet<Table_Blogs> Table_Blogs { get; set; }
        public virtual DbSet<Table_BlogCategory> Table_BlogCategory { get; set; }
        public virtual DbSet<View_BlogNcat> View_BlogNcat { get; set; }
    }
}
