//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Members
    {
        public int MID { get; set; }
        public string MnameFamily { get; set; }
        public string Mpic { get; set; }
        public string Mdes { get; set; }
        public string Mrole { get; set; }
        public string Mphone { get; set; }
        public string Memail { get; set; }
        public string Musername { get; set; }
        public string Mpassword { get; set; }
        public string Mlinkedin { get; set; }
        public string Minstagram { get; set; }
    }
}
