//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Banner
    {
        public int pkID { get; set; }
        public string bannerImage { get; set; }
        public string bannerTitleFa { get; set; }
        public string buttonCaptionFa { get; set; }
        public string bannerAltFa { get; set; }
        public string bannerTitleEn { get; set; }
        public string buttonCaptionEn { get; set; }
        public string siteNameEn { get; set; }
    }
}
