//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Pages
    {
        public int pageID { get; set; }
        public string pageName { get; set; }
        public string pageDes { get; set; }
        public string pageKeywords { get; set; }
        public string pageTitle { get; set; }
    }
}
