//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_UnderOFCounter
    {
        public int pkID { get; set; }
        public string photoPath { get; set; }
        public string aboutTitleFa { get; set; }
        public string aboutParagFa { get; set; }
        public string aboutTitleEn { get; set; }
        public string aboutParagEn { get; set; }
        public string photoAlt { get; set; }
    }
}
