//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_ProjectImage
    {
        public int imageID { get; set; }
        public int projectID { get; set; }
        public string imageUrl { get; set; }
    
        public virtual Table_Projects Table_Projects { get; set; }
    }
}
