//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_ProjTeam
    {
        public int pkID { get; set; }
        public string Title1Fa { get; set; }
        public string Title1En { get; set; }
        public string ButtonCaption1Fa { get; set; }
        public string ButtonCaption1En { get; set; }
        public string Title2Fa { get; set; }
        public string Title2En { get; set; }
        public string ButtonCaption2Fa { get; set; }
        public string ButtonCaption2En { get; set; }
    }
}
